#!/usr/bin/env python3
"""Remove macOS AppleDouble files (names starting with "._") from a folder.

Usage:
    python remove_dot_underscore.py /path/to/folder            # delete, recursively
    python remove_dot_underscore.py /path/to/folder --dry-run  # only list what would be deleted
    python remove_dot_underscore.py /path/to/folder --no-recursive
"""
import argparse
import os
import sys


def find_files(folder, recursive=True):
    """Yield paths of files whose name starts with '._'."""
    if recursive:
        for root, _dirs, files in os.walk(folder):
            for name in files:
                if name.startswith("._"):
                    yield os.path.join(root, name)
    else:
        for name in os.listdir(folder):
            path = os.path.join(folder, name)
            if name.startswith("._") and os.path.isfile(path):
                yield path


def main():
    parser = argparse.ArgumentParser(description="Remove '._*' files generated by macOS.")
    parser.add_argument("folder", help="Folder to clean")
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="List the files without deleting them")
    parser.add_argument("--no-recursive", action="store_true",
                        help="Only look at the top level of the folder")
    args = parser.parse_args()

    if not os.path.isdir(args.folder):
        sys.exit(f"Error: '{args.folder}' is not a directory")

    count = 0
    for path in find_files(args.folder, recursive=not args.no_recursive):
        if args.dry_run:
            print(f"Would remove: {path}")
        else:
            try:
                os.remove(path)
                print(f"Removed: {path}")
            except OSError as exc:
                print(f"Failed: {path} ({exc})", file=sys.stderr)
                continue
        count += 1

    verb = "found" if args.dry_run else "removed"
    print(f"\n{count} file(s) {verb}.")


if __name__ == "__main__":
    main()